# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-30 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='../static/images/default.jpeg', upload_to='media/'),
        ),
    ]
