# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20191026_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
