# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-29 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20191027_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
    ]
