# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_remove_post_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
